<?php exit();?>
Initializing...|info|13
<?php exit();?>
Creating a job to start Backup|info|17
Starting to Backup Database|info|20
Creating softsql|working|23
Adding (L1) : store_commentmeta table|working|50
Adding (L1) : store_comments table|working|50
Adding (L1) : store_links table|working|50
Adding (L1) : store_loginizer_logs table|working|50
Adding (L1) : store_options table|working|50
Adding (L1) : store_postmeta table|working|50
Adding (L1) : store_posts table|working|50
Adding (L1) : store_termmeta table|working|50
Adding (L1) : store_terms table|working|50
Adding (L1) : store_term_relationships table|working|50
Adding (L1) : store_term_taxonomy table|working|50
Adding (L1) : store_usermeta table|working|50
Adding (L1) : store_users table|working|50
Backing up your Wordpress Install|info|39
Starting to create archive|info|60
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/style-engine|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/SimplePie|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/SimplePie/Decode/HTML|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/SimplePie/Content|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/SimplePie/Parse|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/SimplePie/HTTP|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/SimplePie/Cache|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/SimplePie/XML|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/SimplePie/XML/Declaration|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/customize|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/sitemaps/providers|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/Requests/src|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/Requests/src/Exception|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/Requests/src/Transport|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/block-patterns|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/js|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/js/crop|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/js/tinymce|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/js/tinymce/plugins/wplink|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/js/tinymce/plugins/tabfocus|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/js/tinymce/plugins/hr|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/js/tinymce/plugins/wpview|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/js/tinymce/plugins/wpeditimage|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/js/tinymce/skins/lightgray|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/js/tinymce/skins/lightgray/img|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/js/tinymce/skins/wordpress/images|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/js/imgareaselect|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/js/dist|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/js/dist/development|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/js/swfupload|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/images/smilies|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/images/crystal|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/images/media|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/ID3|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/blocks/cover|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/blocks/comment-reply-link|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/blocks/legacy-widget|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/blocks/file|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/blocks/query-pagination-previous|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/blocks/embed|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/blocks/widget-group|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/blocks/query-pagination-next|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/blocks/nextpage|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/blocks/social-link|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/blocks/post-comments-form|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/blocks/comment-template|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/blocks/details|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/blocks/latest-posts|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/blocks/template-part|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/blocks/post-author|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/blocks/query-no-results|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/blocks/post-title|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/blocks/post-author-biography|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/blocks/post-content|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/blocks/navigation-submenu|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/blocks/comments-pagination|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/blocks/table|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/blocks/site-title|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/blocks/social-links|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/blocks/audio|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/blocks/group|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/blocks/site-tagline|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/blocks/archives|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/blocks/query|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/blocks/pullquote|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/blocks/comment-content|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/blocks/comment-date|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/blocks/query-pagination-numbers|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/blocks/html|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/blocks/preformatted|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/blocks/avatar|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/blocks/rss|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/blocks/term-description|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/blocks/post-date|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/blocks/post-terms|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/blocks/post-excerpt|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/fonts|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/sodium_compat/src/Core32/Curve25519|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/sodium_compat/src/Core32/Poly1305|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/sodium_compat/src/Core/Curve25519|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/sodium_compat/src/Core/Poly1305|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/sodium_compat/src/Core/SecretStream|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/sodium_compat/namespaced/Core/Curve25519/Ge|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/sodium_compat/namespaced/Core/Poly1305|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/pomo|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/certificates|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/IXR|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/l10n|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/Text|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/Text/Diff|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/widgets|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/css/dist/commands|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/css/dist/reusable-blocks|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/css/dist/block-directory|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/css/dist/customize-widgets|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/css/dist/editor|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/css/dist/nux|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/css/dist/edit-site|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/css/dist/edit-post|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/css/dist/format-library|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/css/dist/block-library|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/css/dist/preferences|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/css/dist/edit-widgets|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-includes/css/dist/list-reusable-blocks|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/speedycache|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/speedycache/assets|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/speedycache/assets/webfonts|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/speedycache/assets/js|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/gosmtp/main|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/gosmtp/images|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/gosmtp/css|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/main/admin/docs|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/main/admin/page-builders/elementor/inc/controls|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/main/admin/page-builders/elementor/assets|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/main/admin/page-builders/elementor/assets/js|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/main/admin/page-builders/elementor/assets/css|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/main/admin/page-builders/classic|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/main/admin/page-builders/gutenberg|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/main/admin/page-builders/gutenberg/blocks|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/main/admin/page-builders/gutenberg/blocks/breadcrumbs|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/main/admin/page-builders/gutenberg/blocks/faq|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/main/admin/metaboxes|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/main/admin/export|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/main/admin/ajax-migrate|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/main/admin/migrate|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/main/public|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/main/public/editor|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/main/public/editor/primary-category-select|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/main/public/editor/sidebar|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/main/public/editor/blocks|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/main/public/editor/blocks/breadcrumbs|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/main/public/editor/blocks/breadcrumbs/build|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/main/public/editor/blocks/sitemap|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/grpc-gcp/cloudprober/bins/opt|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/grpc-gcp/src|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/grpc-gcp/third_party/googleapis|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/grpc-gcp/doc|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/apiclient|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/apiclient/src/Utils|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/apiclient/src/Service|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/apiclient/src/AuthHandler|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/longrunning/src/LongRunning|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/longrunning/src/ApiCore|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/longrunning/src/ApiCore/LongRunning|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/longrunning/src/ApiCore/LongRunning/resources|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/longrunning/src/ApiCore/LongRunning/Gapic|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/protobuf|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/protobuf/src/GPBMetadata|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/protobuf/src/GPBMetadata/Google|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/protobuf/src/GPBMetadata/Google/Protobuf|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/protobuf/src/GPBMetadata/Google/Protobuf/Internal|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/protobuf/src/Google|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/protobuf/src/Google/Protobuf|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/protobuf/src/Google/Protobuf/Internal/DescriptorProto|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/protobuf/src/Google/Protobuf/Internal/MethodOptions|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/protobuf/src/Google/Protobuf/Internal/FileOptions|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/protobuf/src/Google/Protobuf/Internal/FieldDescriptorProto|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/gax/src|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/gax/src/Transport/Rest|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/gax/src/Middleware|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/gax/metadata|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/gax/metadata/ApiCore/Testing|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/gax/metadata/Google/ApiCore|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/gax/metadata/Google/ApiCore/Tests|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/gax/metadata/Google/ApiCore/Tests/Unit|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/analytics-data|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/analytics-data/src|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/analytics-data/src/V1alpha|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/analytics-data/src/V1alpha/OrderBy/DimensionOrderBy|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/analytics-data/src/V1alpha/DimensionExpression|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/analytics-data/src/V1alpha/resources|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/analytics-data/src/V1alpha/Filter|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/analytics-data/src/V1alpha/Filter/StringFilter|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/analytics-data/src/V1alpha/Filter/NumericFilter|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/analytics-data/src/V1beta/CohortsRange|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/analytics-data/src/V1beta/OrderBy/PivotOrderBy|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/analytics-data/src/V1beta/resources|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/analytics-data/src/V1beta/Filter/NumericFilter|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/analytics-data/metadata/V1Alpha|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/analytics-data/metadata/V1Beta|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/apiclient-services/src|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/apiclient-services/src/AnalyticsReporting|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/apiclient-services/src/Analytics/Resource|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/apiclient-services/src/Indexing|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/apiclient-services/src/Oauth2|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/auth|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/auth/src|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/auth/src/Cache|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/common-protos/src|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/common-protos/src/Rpc|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/common-protos/src/Rpc/Help|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/common-protos/src/Api|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/common-protos/src/Api/Expr|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/common-protos/src/Api/Expr/V1alpha1|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/common-protos/src/Api/Expr/V1alpha1/Expr|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/common-protos/src/Api/Expr/V1alpha1/Decl|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/common-protos/src/Api/Expr/V1alpha1/Decl/FunctionDecl|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/common-protos/src/Api/Expr/V1alpha1/EvalState|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/common-protos/src/Api/Expr/V1beta1/Expr|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/common-protos/src/Api/Expr/V1beta1/Expr/CreateStruct|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/common-protos/src/Api/Distribution|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/common-protos/src/Api/Distribution/BucketOptions|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/common-protos/src/Api/ResourceDescriptor|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/common-protos/src/Api/Property|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/common-protos/src/Cloud/Logging|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/common-protos/src/Cloud/Logging/Type|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/common-protos/src/Cloud/Iam|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/common-protos/src/Cloud/Iam/V1|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/common-protos/src/Cloud/Iam/V1/AuditConfigDelta|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/common-protos/src/Cloud/Iam/V1/BindingDelta|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/common-protos/src/Iam|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/common-protos/src/Iam/V1|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/common-protos/src/Type|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/common-protos/src/Type/PhoneNumber|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/common-protos/metadata|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/common-protos/metadata/Rpc|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/common-protos/metadata/Api|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/common-protos/metadata/Api/Expr/V1Alpha1|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/common-protos/metadata/Cloud|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/common-protos/metadata/Logging|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/common-protos/metadata/Iam|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/common-protos/metadata/Iam/V1|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/google/common-protos/metadata/Iam/V1/Logging|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/psr|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/psr/cache|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/psr/cache/src|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/psr/http-factory|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/monolog/monolog|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/monolog/monolog/src/Monolog|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/monolog/monolog/src/Monolog/Processor|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/paragonie/constant_time_encoding/src|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/paragonie/random_compat|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/paragonie/random_compat/lib|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/paragonie/random_compat/other|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/paragonie/random_compat/dist|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/phpseclib|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/phpseclib/phpseclib/phpseclib/Common|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/phpseclib/phpseclib/phpseclib/System|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/phpseclib/phpseclib/phpseclib/System/SSH|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/phpseclib/phpseclib/phpseclib/System/SSH/Agent|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/phpseclib/phpseclib/phpseclib/System/SSH/Common|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/phpseclib/phpseclib/phpseclib/Crypt|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/phpseclib/phpseclib/phpseclib/Crypt/DH/Formats|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/phpseclib/phpseclib/phpseclib/Crypt/DH/Formats/Keys|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/phpseclib/phpseclib/phpseclib/Crypt/Common|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/phpseclib/phpseclib/phpseclib/Crypt/Common/Formats/Keys|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/phpseclib/phpseclib/phpseclib/Crypt/Common/Formats/Signature|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/phpseclib/phpseclib/phpseclib/Crypt/DSA/Formats|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/phpseclib/phpseclib/phpseclib/Crypt/DSA/Formats/Signature|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/phpseclib/phpseclib/phpseclib/Crypt/EC|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/phpseclib/phpseclib/phpseclib/Crypt/EC/Formats/Signature|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/phpseclib/phpseclib/phpseclib/Crypt/EC/Curves|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/phpseclib/phpseclib/phpseclib/Exception|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/phpseclib/phpseclib/phpseclib/File|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/phpseclib/phpseclib/phpseclib/File/ASN1|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/phpseclib/phpseclib/phpseclib/Math|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/phpseclib/phpseclib/phpseclib/Math/BigInteger|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/phpseclib/phpseclib/phpseclib/Math/BigInteger/Engines|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/phpseclib/phpseclib/phpseclib/Math/BigInteger/Engines/PHP|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/phpseclib/phpseclib/phpseclib/Math/BigInteger/Engines/BCMath|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/phpseclib/phpseclib/phpseclib/Math/Common/FiniteField|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/phpseclib/phpseclib/phpseclib/Math/BinaryField|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/phpseclib/phpseclib/phpseclib/Math/PrimeField|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/ralouphie|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/ralouphie/getallheaders|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/ralouphie/getallheaders/src|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/firebase|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/symfony|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/symfony/deprecation-contracts|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/guzzlehttp|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/guzzlehttp/promises|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/guzzlehttp/guzzle/src/Cookie|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/grpc/grpc/src|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/grpc/grpc/src/lib|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/grpc/grpc/src/lib/Internal|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/vendor/grpc/grpc/etc|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/templates|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/templates/json-schemas|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/assets|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/assets/js|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/assets/css|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/classes|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/classes/Actions/Api|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/classes/Actions/Api/Metas|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/classes/Actions/Api/Options|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/classes/Actions/Front|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/classes/Actions/Options|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/classes/Actions/Admin|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/classes/Actions/Admin/Importer|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/classes/Core/Container|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/classes/Core/Hooks|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/classes/Models|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/classes/Compose|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/classes/Constants|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/classes/Services/Metas|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/classes/Services/Settings|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/classes/Services/Settings/Roles|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/classes/Services/ContentAnalysis/GetContent/OG|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/classes/Services/ContentAnalysis/GetContent/Twitter|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/classes/Tags/Schema|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/classes/Tags/Schema/SocialAccount|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/classes/Tags/Custom|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/classes/Thirds/RankMath|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/classes/Thirds/WooCommerce|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/classes/Thirds/ACF|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/classes/Thirds/MainWP|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/classes/ManualHooks/Thirds/WooCommerce|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/siteseo/classes/Helpers/Metas|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/akismet/_inc/rtl|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/akismet/_inc/fonts|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/loginizer/lib|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/loginizer/lib/IPv6|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/loginizer/assets|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/loginizer/assets/js|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/loginizer/assets/images|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/loginizer/assets/css|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/fileorganizer|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/fileorganizer/js|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/fileorganizer/manager|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/fileorganizer/manager/img|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/fileorganizer/manager/js|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/fileorganizer/manager/js/extras|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/fileorganizer/manager/js/i18n|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/fileorganizer/manager/js/i18n/help|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/fileorganizer/manager/themes/windows10/js|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/fileorganizer/manager/themes/windows10/images/16px|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/fileorganizer/manager/themes/material|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/fileorganizer/manager/themes/material/css|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/fileorganizer/manager/themes/dark|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/fileorganizer/manager/themes/dark/css|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/fileorganizer/manager/themes/material-dark|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/fileorganizer/manager/php|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/fileorganizer/manager/php/plugins/AutoResize|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/fileorganizer/manager/php/editors|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/fileorganizer/manager/php/editors/ZipArchive|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/fileorganizer/manager/php/editors/OnlineConvert|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/fileorganizer/manager/php/editors/ZohoOffice|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/fileorganizer/manager/php/libs|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/fileorganizer/css|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/speedycache-pro/main|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/speedycache-pro/assets/js|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/speedycache-pro/assets/images|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/backuply/main|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/backuply/lib/Curl|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/backuply/assets|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/backuply/assets/css|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/plugins/classic-editor/js|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/cache|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/cache/speedycache|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/cache/speedycache/sincehence.store|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/themes/twentytwentythree|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/themes/twentytwentythree/parts|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/themes/twentytwentythree/assets|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/themes/twentytwentythree/assets/fonts/source-serif-pro|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/themes/twentytwentythree/assets/fonts/inter|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/themes/twentytwentythree/patterns|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/themes/twentytwentythree/styles|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/themes/twentytwentyfour/templates|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/themes/twentytwentyfour/assets/images|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/themes/twentytwentyfour/assets/fonts|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/themes/twentytwentyfour/assets/fonts/instrument-sans|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/themes/twentytwentyfour/assets/css|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/themes/twentytwentyfour/patterns|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/themes/twentytwentytwo|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/themes/twentytwentytwo/inc|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/themes/twentytwentytwo/assets|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/themes/twentytwentytwo/assets/fonts|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/themes/twentytwentytwo/assets/fonts/source-serif-pro|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/themes/twentytwentytwo/assets/fonts/inter|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-content/themes/twentytwentytwo/assets/videos|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-admin/maint|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-admin/js/widgets|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-admin/images|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-admin/user|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-admin/css/colors|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-admin/css/colors/modern|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-admin/css/colors/midnight|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-admin/css/colors/light|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-admin/css/colors/coffee|adding|65
Adding (L1) : /home/yzwigndt/maxmix_html/wp-admin/css/colors/ectoplasm|adding|65
Archive created with a file size of 29.93 MB|info|100
Backup Successfully Completed|success|100
